// packages/app3/src/App.vue
<template>
	<Counter :globalEventDistributor="globalEventDistributor"/>
</template>

<script lang="ts">
import Counter from './components/Counter.vue';
import { Vue } from "vue-class-component";

import { Model, Options, Prop } from "vue-property-decorator";
import store from './store';

@Options({
	name: "App",
	components: {Counter},
})
export default class App extends Vue {
	@Prop()
	globalEventDistributor: any;
}
</script>

// packages/app2/src/App.tsx
import { Provider } from "react-redux";
import { Counter } from "./components/counter/Counter";
import store from "./store/index";
import "./index.scss";
import React from "react";

export const App: any = (props: any): JSX.Element => (
	<div>
		<Provider store={store}>
			<h1>react {props.name}</h1>
			<Counter />
		</Provider>
	</div>
);
