// packages/app3/src/components/Counter.vue
<template>
	<div>
		<h1>Vue app</h1>
		{{ counter }}
		<button @click="increment">Increment</button>
		<h2>Global counter</h2>
		{{ globalEventDistributor.globalStore.counter }}
		<button @click="globalEventDistributor.globalStore.counter++">IncrementGlobal</button>
	</div>
</template>

<script lang="ts">
import store from '../store';
import { defineComponent } from 'vue';
import { Prop, Options,  Watch } from "vue-property-decorator";
import { Vue } from "vue-class-component";

@Options({name: "Counter"})
export default class Counter extends Vue {
	@Prop()
	globalEventDistributor: any;
	

	get counter() {
		return store.state.counter;
	}

	increment() {
		store.dispatch('counterIncrement');
	}
};
</script>

// packages/app1/src/app/counter/counter.component.ts
import {Component} from "@angular/core";
import {Observable} from "rxjs";
import {CounterService} from "./counter.service";
import {CounterActions} from "./counter.actions";
import {globalEventDistributor} from "src/single-spa/single-spa-props";
import {Store} from "@ngrx/store";
import {AppState} from "../app.state";

@Component({
	selector: "app-counter",
	template: `
		<div>
			<p>Counter: {{ counterCurrent | async }}</p>
			<p>Counter: {{ globalStore ? globalStore.counter : 0 }}</p>
			<button (click)="actions.increment()">increment</button>
			<button (click)="actions.incrementGlobal()">increment global</button>
		</div>
	`,
})
export class CounterComponent {
	public counterCurrent: Observable<number>;
	public globalStore: any;

	constructor(counterService: CounterService, public actions: CounterActions, private store: Store<AppState>) {
		this.counterCurrent = counterService.getCounterCurrent();
		if (globalEventDistributor) this.globalStore = globalEventDistributor.globalStore;
	}
}
