// packages/app3/src/components/Counter.vue
<template>
	<div>
		<h1>vue app3</h1>
		<h2>Local Counter {{ counter }}</h2>
		<h2>Global Counter {{ globalEventDistributor.globalStore.counter }}</h2>
		<ui-button @click="increment">increment</ui-button>
		<ui-button @click="globalEventDistributor.globalStore.counter++">increment global</ui-button>
	</div>
</template>

<script lang="ts">
import store from "../store";
import { Prop, Options, Watch } from "vue-property-decorator";
import { Vue } from "vue-class-component";
import { GlobalEventDistributerModel } from "@/models/GlobalEventDistributerModel";

import { UiButton } from "@xotoboil-multifront/ui-vue";

@Options({ name: "Counter", components: { UiButton } })
export default class Counter extends Vue {
	@Prop()
	globalEventDistributor: GlobalEventDistributerModel;

	get counter() {
		return store.state.counter;
	}

	increment() {
		store.dispatch("counterIncrement");
	}
}
</script>

// packages/app2/src/components/counter/Counter.tsx
import React, { useState } from "react";
import { useSelector } from "react-redux";
import { UiButton } from "@xotoboil-multifront/ui-react";
import { CounterModel } from "@/models/CounterModel";
import store, { getGlobalEventDistributer } from "@/store";

export const Counter: any = (props: any): JSX.Element => {
	const localCounter = useSelector((state: CounterModel) => state.counter.counter);
	const [globalEventDistributerCounter, setGlobalEventDistributerCounterState] = useState(getGlobalEventDistributer() ? getGlobalEventDistributer().globalStore.counter : 0);
	const setGlobalEventDistributerCounter = (value: number) => {
		setGlobalEventDistributerCounterState(value);
		getGlobalEventDistributer().globalStore.counter + 1;
	};

	return (
		<div>
			<h2>Local Counter: {localCounter}</h2>
			<h2>Global Counter: {globalEventDistributerCounter}</h2>
			<UiButton onClick={() => store.dispatch({ type: "counter/counterIncrement" })}>increment</UiButton>
			<UiButton onClick={() => setGlobalEventDistributerCounter(globalEventDistributerCounter + 1)}>increment global</UiButton>
		</div>
	);
};
